version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  build:
    commands:
      - dotnet build -c Release
  post_build:
    commands:
      - dotnet publish -c Release -o ./build_output ./AWSCodePipelineDemo/AWSCodePipelineDemo.csproj --self-contained false
      - cp Procfile ./build_output
artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no
